#!/usr/bin/env python3
"""Rebuild the web app's data + assets.

Sources (both inside the Unity zip):
  AUDIO : unlimitchords/Assets/Resources/Audio/*.mp3   (456 files, the chord recordings)
  DIAG  : unlimitchords/Assets/Resources/Sprites/*.png  (chord diagrams)

Rules:
  * Buttons are driven by the MP3 filenames (Greg: "name the button the same as the file").
  * Each mp3 -> assets/audio/chords/<ROOT>/<label>.mp3
  * Diagram lookup: normalized label (Maj->M) matches the PNG base name.
  * Root note has NO recording -> synthesized jazz-guitar pluck in app.js (rootAudio: null).
"""
import os, shutil, json, re

SRC_AUDIO = "/workspaces/hermes/greg/projects/unlimit-chords/unlimitchords/Assets/Resources/Audio"
SRC_DIAG = "/workspaces/hermes/greg/projects/unlimit-chords/unlimitchords/Assets/Resources/Sprites"
OUT = "/workspaces/hermes/greg/projects/guitarchordsfree"

ROOTS = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"]
FLAT = ["Db", "Eb", "Gb", "Ab", "Bb"]
NAT = ["C", "D", "E", "F", "G", "A", "B"]

def ensure(p): os.makedirs(p, exist_ok=True)

def parse_root(name):
    # try flats first (e.g. "Ab7" -> Ab), then naturals
    for r in FLAT:
        if name.startswith(r): return r
    for r in NAT:
        if name.startswith(r): return r
    return None

def normalize(label):
    # diagram PNGs use "M" where audio uses "Maj" in a few names (e.g. AbM7sus4 vs AbMaj7sus4)
    return label.replace("Maj", "M")

# ---- build a robust diagram lookup: root -> {match_key: png_path} ----
# keys: exact name, lowercased name, and Maj->M lowercased name (case-insensitive friendly)
diag_lookup = {}   # root -> dict(lower_key -> src_png)
for fn in os.listdir(SRC_DIAG):
    if not fn.lower().endswith(".png"): continue
    base = fn[:-4]
    r = parse_root(base)
    if r is None: continue
    d = diag_lookup.setdefault(r, {})
    d[base.lower()] = os.path.join(SRC_DIAG, fn)
    d[normalize(base).lower()] = os.path.join(SRC_DIAG, fn)

def find_diagram(root, label):
    d = diag_lookup.get(root, {})
    # 1) exact (case-sensitive)
    if label in d: return d[label]
    # 2) case-insensitive
    key = label.lower()
    if key in d: return d[key]
    # 3) Maj->M, case-insensitive (jazzer casing slips)
    key2 = normalize(label).lower()
    if key2 in d: return d[key2]
    return None

# ---- copy diagrams (by normalized name) so they live next to nothing; we keep originals ----
diag_out = os.path.join(OUT, "assets", "diagrams")
for r in ROOTS:
    d = os.path.join(diag_out, r); ensure(d)
# we will copy the png whose base matches the normalized label at wiring time

# ---- build DATA from mp3s ----
DATA = {}
for r in ROOTS:
    entry = {"rootAudio": None, "chords": []}
    chord_dir = os.path.join(OUT, "assets", "audio", "chords", r); ensure(chord_dir)
    # find mp3s for this root
    labels = []
    for fn in os.listdir(SRC_AUDIO):
        if not fn.lower().endswith(".mp3"): continue
        base = fn[:-4]
        if parse_root(base) != r: continue
        labels.append(base)
    labels.sort(key=lambda L: (len(L), L))
    for label in labels:
        src = os.path.join(SRC_AUDIO, label + ".mp3")
        dst = os.path.join(chord_dir, label + ".mp3")
        shutil.copyfile(src, dst)
        audio = f"assets/audio/chords/{r}/{label}.mp3"
        # diagram: robust match (exact / case-insensitive / Maj->M)
        cand = find_diagram(r, label)
        if not cand:
            # no diagram -> skip this button entirely (audio-only chords not shown)
            continue
        # copy the matched diagram under the chord label (preserve its real filename)
        diag_base = os.path.basename(cand)[:-4]
        dd = os.path.join(diag_out, r, diag_base + ".png")
        shutil.copyfile(cand, dd)
        diagram = f"assets/diagrams/{r}/{diag_base}.png"
        entry["chords"].append({"type": "", "label": label, "audio": audio, "diagram": diagram})
    DATA[r] = entry

with open(os.path.join(OUT, "data.js"), "w") as f:
    f.write("// AUTO-GENERATED by build_assets.py — do not edit by hand.\n")
    f.write("const ROOTS = " + json.dumps(ROOTS) + ";\n")
    f.write("const DATA = " + json.dumps(DATA, indent=1) + ";\n")
    f.write("if (typeof module !== 'undefined') module.exports = { ROOTS, DATA };\n")

# ---- report ----
total = sum(len(d["chords"]) for d in DATA.values())
with_diag = sum(1 for d in DATA.values() for c in d["chords"] if c["diagram"])
print(f"roots: {len(ROOTS)}")
print(f"chord buttons added (mp3 + diagram): {total}")
print(f"  with audio: {total} (all real mp3 recordings)")
print(f"  with diagram: {with_diag}")
print(f"chords skipped (no diagram): {456 - total}")
print("wrote data.js")
