// AUTO-GENERATED by build_assets.py — do not edit by hand.
const ROOTS = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"];
const DATA = {
 "C": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "C",
    "audio": "assets/audio/chords/C/C.mp3",
    "diagram": "assets/diagrams/C/C.png"
   },
   {
    "type": "",
    "label": "C6",
    "audio": "assets/audio/chords/C/C6.mp3",
    "diagram": "assets/diagrams/C/C6.png"
   },
   {
    "type": "",
    "label": "C7",
    "audio": "assets/audio/chords/C/C7.mp3",
    "diagram": "assets/diagrams/C/C7.png"
   },
   {
    "type": "",
    "label": "C9",
    "audio": "assets/audio/chords/C/C9.mp3",
    "diagram": "assets/diagrams/C/C9.png"
   },
   {
    "type": "",
    "label": "Cm",
    "audio": "assets/audio/chords/C/Cm.mp3",
    "diagram": "assets/diagrams/C/Cm.png"
   },
   {
    "type": "",
    "label": "C11",
    "audio": "assets/audio/chords/C/C11.mp3",
    "diagram": "assets/diagrams/C/C11.png"
   },
   {
    "type": "",
    "label": "C13",
    "audio": "assets/audio/chords/C/C13.mp3",
    "diagram": "assets/diagrams/C/C13.png"
   },
   {
    "type": "",
    "label": "C69",
    "audio": "assets/audio/chords/C/C69.mp3",
    "diagram": "assets/diagrams/C/C69.png"
   },
   {
    "type": "",
    "label": "Cm6",
    "audio": "assets/audio/chords/C/Cm6.mp3",
    "diagram": "assets/diagrams/C/Cm6.png"
   },
   {
    "type": "",
    "label": "Cm7",
    "audio": "assets/audio/chords/C/Cm7.mp3",
    "diagram": "assets/diagrams/C/Cm7.png"
   },
   {
    "type": "",
    "label": "Cm9",
    "audio": "assets/audio/chords/C/Cm9.mp3",
    "diagram": "assets/diagrams/C/Cm9.png"
   },
   {
    "type": "",
    "label": "Caug",
    "audio": "assets/audio/chords/C/Caug.mp3",
    "diagram": "assets/diagrams/C/Caug.png"
   },
   {
    "type": "",
    "label": "Cdim",
    "audio": "assets/audio/chords/C/Cdim.mp3",
    "diagram": "assets/diagrams/C/Cdim.png"
   },
   {
    "type": "",
    "label": "Cm69",
    "audio": "assets/audio/chords/C/Cm69.mp3",
    "diagram": "assets/diagrams/C/Cm69.png"
   },
   {
    "type": "",
    "label": "Cadd9",
    "audio": "assets/audio/chords/C/Cadd9.mp3",
    "diagram": "assets/diagrams/C/Cadd9.png"
   },
   {
    "type": "",
    "label": "Cdim7",
    "audio": "assets/audio/chords/C/Cdim7.mp3",
    "diagram": "assets/diagrams/C/Cdim7.png"
   },
   {
    "type": "",
    "label": "Cmaj7",
    "audio": "assets/audio/chords/C/Cmaj7.mp3",
    "diagram": "assets/diagrams/C/Cmaj7.png"
   },
   {
    "type": "",
    "label": "Cmaj9",
    "audio": "assets/audio/chords/C/Cmaj9.mp3",
    "diagram": "assets/diagrams/C/Cmaj9.png"
   },
   {
    "type": "",
    "label": "Csus2",
    "audio": "assets/audio/chords/C/Csus2.mp3",
    "diagram": "assets/diagrams/C/Csus2.png"
   },
   {
    "type": "",
    "label": "Csus4",
    "audio": "assets/audio/chords/C/Csus4.mp3",
    "diagram": "assets/diagrams/C/Csus4.png"
   },
   {
    "type": "",
    "label": "C7sus4",
    "audio": "assets/audio/chords/C/C7sus4.mp3",
    "diagram": "assets/diagrams/C/C7sus4.png"
   },
   {
    "type": "",
    "label": "C9sus4",
    "audio": "assets/audio/chords/C/C9sus4.mp3",
    "diagram": "assets/diagrams/C/C9sus4.png"
   },
   {
    "type": "",
    "label": "CmMaj7",
    "audio": "assets/audio/chords/C/CmMaj7.mp3",
    "diagram": "assets/diagrams/C/CmMaj7.png"
   },
   {
    "type": "",
    "label": "CmMaj9",
    "audio": "assets/audio/chords/C/CmMaj9.mp3",
    "diagram": "assets/diagrams/C/CmMaj9.png"
   },
   {
    "type": "",
    "label": "Cmadd9",
    "audio": "assets/audio/chords/C/Cmadd9.mp3",
    "diagram": "assets/diagrams/C/Cmadd9.png"
   },
   {
    "type": "",
    "label": "C7flat5",
    "audio": "assets/audio/chords/C/C7flat5.mp3",
    "diagram": "assets/diagrams/C/C7flat5.png"
   },
   {
    "type": "",
    "label": "C7flat9",
    "audio": "assets/audio/chords/C/C7flat9.mp3",
    "diagram": "assets/diagrams/C/C7flat9.png"
   },
   {
    "type": "",
    "label": "C7flat13",
    "audio": "assets/audio/chords/C/C7flat13.mp3",
    "diagram": "assets/diagrams/C/C7flat13.png"
   },
   {
    "type": "",
    "label": "C7sharp5",
    "audio": "assets/audio/chords/C/C7sharp5.mp3",
    "diagram": "assets/diagrams/C/C7sharp5.png"
   },
   {
    "type": "",
    "label": "C7sharp9",
    "audio": "assets/audio/chords/C/C7sharp9.mp3",
    "diagram": "assets/diagrams/C/C7sharp9.png"
   },
   {
    "type": "",
    "label": "Cm7flat5",
    "audio": "assets/audio/chords/C/Cm7flat5.mp3",
    "diagram": "assets/diagrams/C/Cm7flat5.png"
   },
   {
    "type": "",
    "label": "Cmsharp5",
    "audio": "assets/audio/chords/C/Cmsharp5.mp3",
    "diagram": "assets/diagrams/C/Cmsharp5.png"
   },
   {
    "type": "",
    "label": "C7sharp11",
    "audio": "assets/audio/chords/C/C7sharp11.mp3",
    "diagram": "assets/diagrams/C/C7sharp11.png"
   },
   {
    "type": "",
    "label": "CMaj7sus4",
    "audio": "assets/audio/chords/C/CMaj7sus4.mp3",
    "diagram": "assets/diagrams/C/CMaj7sus4.png"
   },
   {
    "type": "",
    "label": "Cm7sharp5",
    "audio": "assets/audio/chords/C/Cm7sharp5.mp3",
    "diagram": "assets/diagrams/C/Cm7sharp5.png"
   },
   {
    "type": "",
    "label": "Cmaj9sus4",
    "audio": "assets/audio/chords/C/Cmaj9sus4.mp3",
    "diagram": "assets/diagrams/C/Cmaj9sus4.png"
   },
   {
    "type": "",
    "label": "Cmaj7flat5",
    "audio": "assets/audio/chords/C/Cmaj7flat5.mp3",
    "diagram": "assets/diagrams/C/Cmaj7flat5.png"
   },
   {
    "type": "",
    "label": "Cmaj7sharp5",
    "audio": "assets/audio/chords/C/Cmaj7sharp5.mp3",
    "diagram": "assets/diagrams/C/Cmaj7sharp5.png"
   }
  ]
 },
 "Db": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "Db",
    "audio": "assets/audio/chords/Db/Db.mp3",
    "diagram": "assets/diagrams/Db/Db.png"
   },
   {
    "type": "",
    "label": "Db6",
    "audio": "assets/audio/chords/Db/Db6.mp3",
    "diagram": "assets/diagrams/Db/Db6.png"
   },
   {
    "type": "",
    "label": "Db7",
    "audio": "assets/audio/chords/Db/Db7.mp3",
    "diagram": "assets/diagrams/Db/Db7.png"
   },
   {
    "type": "",
    "label": "Db9",
    "audio": "assets/audio/chords/Db/Db9.mp3",
    "diagram": "assets/diagrams/Db/Db9.png"
   },
   {
    "type": "",
    "label": "Dbm",
    "audio": "assets/audio/chords/Db/Dbm.mp3",
    "diagram": "assets/diagrams/Db/Dbm.png"
   },
   {
    "type": "",
    "label": "Db11",
    "audio": "assets/audio/chords/Db/Db11.mp3",
    "diagram": "assets/diagrams/Db/Db11.png"
   },
   {
    "type": "",
    "label": "Db13",
    "audio": "assets/audio/chords/Db/Db13.mp3",
    "diagram": "assets/diagrams/Db/Db13.png"
   },
   {
    "type": "",
    "label": "Db69",
    "audio": "assets/audio/chords/Db/Db69.mp3",
    "diagram": "assets/diagrams/Db/Db69.png"
   },
   {
    "type": "",
    "label": "Dbm6",
    "audio": "assets/audio/chords/Db/Dbm6.mp3",
    "diagram": "assets/diagrams/Db/Dbm6.png"
   },
   {
    "type": "",
    "label": "Dbm7",
    "audio": "assets/audio/chords/Db/Dbm7.mp3",
    "diagram": "assets/diagrams/Db/Dbm7.png"
   },
   {
    "type": "",
    "label": "Dbm9",
    "audio": "assets/audio/chords/Db/Dbm9.mp3",
    "diagram": "assets/diagrams/Db/DbMaj9.png"
   },
   {
    "type": "",
    "label": "Dbaug",
    "audio": "assets/audio/chords/Db/Dbaug.mp3",
    "diagram": "assets/diagrams/Db/Dbaug.png"
   },
   {
    "type": "",
    "label": "Dbdim",
    "audio": "assets/audio/chords/Db/Dbdim.mp3",
    "diagram": "assets/diagrams/Db/Dbdim.png"
   },
   {
    "type": "",
    "label": "Dbm69",
    "audio": "assets/audio/chords/Db/Dbm69.mp3",
    "diagram": "assets/diagrams/Db/Dbm69.png"
   },
   {
    "type": "",
    "label": "Dbadd9",
    "audio": "assets/audio/chords/Db/Dbadd9.mp3",
    "diagram": "assets/diagrams/Db/Dbadd9.png"
   },
   {
    "type": "",
    "label": "Dbdim7",
    "audio": "assets/audio/chords/Db/Dbdim7.mp3",
    "diagram": "assets/diagrams/Db/Dbdim7.png"
   },
   {
    "type": "",
    "label": "Dbmaj7",
    "audio": "assets/audio/chords/Db/Dbmaj7.mp3",
    "diagram": "assets/diagrams/Db/DbMaj7.png"
   },
   {
    "type": "",
    "label": "Dbmaj9",
    "audio": "assets/audio/chords/Db/Dbmaj9.mp3",
    "diagram": "assets/diagrams/Db/DbMaj9.png"
   },
   {
    "type": "",
    "label": "Dbsus2",
    "audio": "assets/audio/chords/Db/Dbsus2.mp3",
    "diagram": "assets/diagrams/Db/Dbsus2.png"
   },
   {
    "type": "",
    "label": "Dbsus4",
    "audio": "assets/audio/chords/Db/Dbsus4.mp3",
    "diagram": "assets/diagrams/Db/Dbsus4.png"
   },
   {
    "type": "",
    "label": "Db7sus4",
    "audio": "assets/audio/chords/Db/Db7sus4.mp3",
    "diagram": "assets/diagrams/Db/Db7sus4.png"
   },
   {
    "type": "",
    "label": "Db9sus4",
    "audio": "assets/audio/chords/Db/Db9sus4.mp3",
    "diagram": "assets/diagrams/Db/Db9sus4.png"
   },
   {
    "type": "",
    "label": "DbmMaj7",
    "audio": "assets/audio/chords/Db/DbmMaj7.mp3",
    "diagram": "assets/diagrams/Db/DbmMaj7.png"
   },
   {
    "type": "",
    "label": "DbmMaj9",
    "audio": "assets/audio/chords/Db/DbmMaj9.mp3",
    "diagram": "assets/diagrams/Db/DbmMaj9.png"
   },
   {
    "type": "",
    "label": "Dbmadd9",
    "audio": "assets/audio/chords/Db/Dbmadd9.mp3",
    "diagram": "assets/diagrams/Db/Dbmadd9.png"
   },
   {
    "type": "",
    "label": "Db7flat5",
    "audio": "assets/audio/chords/Db/Db7flat5.mp3",
    "diagram": "assets/diagrams/Db/Db7flat5.png"
   },
   {
    "type": "",
    "label": "Db7flat9",
    "audio": "assets/audio/chords/Db/Db7flat9.mp3",
    "diagram": "assets/diagrams/Db/Db7flat9.png"
   },
   {
    "type": "",
    "label": "Db7flat13",
    "audio": "assets/audio/chords/Db/Db7flat13.mp3",
    "diagram": "assets/diagrams/Db/Db7flat13.png"
   },
   {
    "type": "",
    "label": "Db7sharp5",
    "audio": "assets/audio/chords/Db/Db7sharp5.mp3",
    "diagram": "assets/diagrams/Db/Db7sharp5.png"
   },
   {
    "type": "",
    "label": "Db7sharp9",
    "audio": "assets/audio/chords/Db/Db7sharp9.mp3",
    "diagram": "assets/diagrams/Db/Db7sharp9.png"
   },
   {
    "type": "",
    "label": "Dbm7flat5",
    "audio": "assets/audio/chords/Db/Dbm7flat5.mp3",
    "diagram": "assets/diagrams/Db/Dbm7flat5.png"
   },
   {
    "type": "",
    "label": "Dbmsharp5",
    "audio": "assets/audio/chords/Db/Dbmsharp5.mp3",
    "diagram": "assets/diagrams/Db/Dbmsharp5.png"
   },
   {
    "type": "",
    "label": "Db7sharp11",
    "audio": "assets/audio/chords/Db/Db7sharp11.mp3",
    "diagram": "assets/diagrams/Db/Db7sharp11.png"
   },
   {
    "type": "",
    "label": "DbMaj7sus4",
    "audio": "assets/audio/chords/Db/DbMaj7sus4.mp3",
    "diagram": "assets/diagrams/Db/DbMaj7sus4.png"
   },
   {
    "type": "",
    "label": "DbMaj9sus4",
    "audio": "assets/audio/chords/Db/DbMaj9sus4.mp3",
    "diagram": "assets/diagrams/Db/DbMaj9sus4.png"
   },
   {
    "type": "",
    "label": "Dbm7sharp5",
    "audio": "assets/audio/chords/Db/Dbm7sharp5.mp3",
    "diagram": "assets/diagrams/Db/Dbm7sharp5.png"
   },
   {
    "type": "",
    "label": "Dbmaj7flat5",
    "audio": "assets/audio/chords/Db/Dbmaj7flat5.mp3",
    "diagram": "assets/diagrams/Db/DbMaj7flat5.png"
   },
   {
    "type": "",
    "label": "Dbmaj7sharp5",
    "audio": "assets/audio/chords/Db/Dbmaj7sharp5.mp3",
    "diagram": "assets/diagrams/Db/DbMaj7sharp5.png"
   }
  ]
 },
 "D": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "D",
    "audio": "assets/audio/chords/D/D.mp3",
    "diagram": "assets/diagrams/D/D.png"
   },
   {
    "type": "",
    "label": "D6",
    "audio": "assets/audio/chords/D/D6.mp3",
    "diagram": "assets/diagrams/D/D6.png"
   },
   {
    "type": "",
    "label": "D7",
    "audio": "assets/audio/chords/D/D7.mp3",
    "diagram": "assets/diagrams/D/D7.png"
   },
   {
    "type": "",
    "label": "D9",
    "audio": "assets/audio/chords/D/D9.mp3",
    "diagram": "assets/diagrams/D/D9.png"
   },
   {
    "type": "",
    "label": "Dm",
    "audio": "assets/audio/chords/D/Dm.mp3",
    "diagram": "assets/diagrams/D/Dm.png"
   },
   {
    "type": "",
    "label": "D11",
    "audio": "assets/audio/chords/D/D11.mp3",
    "diagram": "assets/diagrams/D/D11.png"
   },
   {
    "type": "",
    "label": "D13",
    "audio": "assets/audio/chords/D/D13.mp3",
    "diagram": "assets/diagrams/D/D13.png"
   },
   {
    "type": "",
    "label": "D69",
    "audio": "assets/audio/chords/D/D69.mp3",
    "diagram": "assets/diagrams/D/D69.png"
   },
   {
    "type": "",
    "label": "Dm6",
    "audio": "assets/audio/chords/D/Dm6.mp3",
    "diagram": "assets/diagrams/D/Dm6.png"
   },
   {
    "type": "",
    "label": "Dm7",
    "audio": "assets/audio/chords/D/Dm7.mp3",
    "diagram": "assets/diagrams/D/Dm7.png"
   },
   {
    "type": "",
    "label": "Dm9",
    "audio": "assets/audio/chords/D/Dm9.mp3",
    "diagram": "assets/diagrams/D/Dm9.png"
   },
   {
    "type": "",
    "label": "Daug",
    "audio": "assets/audio/chords/D/Daug.mp3",
    "diagram": "assets/diagrams/D/Daug.png"
   },
   {
    "type": "",
    "label": "Ddim",
    "audio": "assets/audio/chords/D/Ddim.mp3",
    "diagram": "assets/diagrams/D/Ddim.png"
   },
   {
    "type": "",
    "label": "Dm69",
    "audio": "assets/audio/chords/D/Dm69.mp3",
    "diagram": "assets/diagrams/D/Dm69.png"
   },
   {
    "type": "",
    "label": "Dadd9",
    "audio": "assets/audio/chords/D/Dadd9.mp3",
    "diagram": "assets/diagrams/D/Dadd9.png"
   },
   {
    "type": "",
    "label": "Ddim7",
    "audio": "assets/audio/chords/D/Ddim7.mp3",
    "diagram": "assets/diagrams/D/Ddim7.png"
   },
   {
    "type": "",
    "label": "Dmaj7",
    "audio": "assets/audio/chords/D/Dmaj7.mp3",
    "diagram": "assets/diagrams/D/Dmaj7.png"
   },
   {
    "type": "",
    "label": "Dmaj9",
    "audio": "assets/audio/chords/D/Dmaj9.mp3",
    "diagram": "assets/diagrams/D/Dmaj9.png"
   },
   {
    "type": "",
    "label": "Dsus2",
    "audio": "assets/audio/chords/D/Dsus2.mp3",
    "diagram": "assets/diagrams/D/Dsus2.png"
   },
   {
    "type": "",
    "label": "Dsus4",
    "audio": "assets/audio/chords/D/Dsus4.mp3",
    "diagram": "assets/diagrams/D/Dsus4.png"
   },
   {
    "type": "",
    "label": "D7sus4",
    "audio": "assets/audio/chords/D/D7sus4.mp3",
    "diagram": "assets/diagrams/D/D7sus4.png"
   },
   {
    "type": "",
    "label": "D9sus4",
    "audio": "assets/audio/chords/D/D9sus4.mp3",
    "diagram": "assets/diagrams/D/D9sus4.png"
   },
   {
    "type": "",
    "label": "DmMaj7",
    "audio": "assets/audio/chords/D/DmMaj7.mp3",
    "diagram": "assets/diagrams/D/DmMaj7.png"
   },
   {
    "type": "",
    "label": "DmMaj9",
    "audio": "assets/audio/chords/D/DmMaj9.mp3",
    "diagram": "assets/diagrams/D/DmMaj9.png"
   },
   {
    "type": "",
    "label": "Dmadd9",
    "audio": "assets/audio/chords/D/Dmadd9.mp3",
    "diagram": "assets/diagrams/D/Dmadd9.png"
   },
   {
    "type": "",
    "label": "D7flat5",
    "audio": "assets/audio/chords/D/D7flat5.mp3",
    "diagram": "assets/diagrams/D/D7flat5.png"
   },
   {
    "type": "",
    "label": "D7flat9",
    "audio": "assets/audio/chords/D/D7flat9.mp3",
    "diagram": "assets/diagrams/D/D7flat9.png"
   },
   {
    "type": "",
    "label": "D7flat13",
    "audio": "assets/audio/chords/D/D7flat13.mp3",
    "diagram": "assets/diagrams/D/D7flat13.png"
   },
   {
    "type": "",
    "label": "D7sharp5",
    "audio": "assets/audio/chords/D/D7sharp5.mp3",
    "diagram": "assets/diagrams/D/D7sharp5.png"
   },
   {
    "type": "",
    "label": "D7sharp9",
    "audio": "assets/audio/chords/D/D7sharp9.mp3",
    "diagram": "assets/diagrams/D/D7sharp9.png"
   },
   {
    "type": "",
    "label": "Dm7flat5",
    "audio": "assets/audio/chords/D/Dm7flat5.mp3",
    "diagram": "assets/diagrams/D/Dm7flat5.png"
   },
   {
    "type": "",
    "label": "Dmsharp5",
    "audio": "assets/audio/chords/D/Dmsharp5.mp3",
    "diagram": "assets/diagrams/D/Dmsharp5.png"
   },
   {
    "type": "",
    "label": "D7sharp11",
    "audio": "assets/audio/chords/D/D7sharp11.mp3",
    "diagram": "assets/diagrams/D/D7sharp11.png"
   },
   {
    "type": "",
    "label": "DMaj7sus4",
    "audio": "assets/audio/chords/D/DMaj7sus4.mp3",
    "diagram": "assets/diagrams/D/DMaj7sus4.png"
   },
   {
    "type": "",
    "label": "Dm7sharp5",
    "audio": "assets/audio/chords/D/Dm7sharp5.mp3",
    "diagram": "assets/diagrams/D/Dm7sharp5.png"
   },
   {
    "type": "",
    "label": "Dmaj9sus4",
    "audio": "assets/audio/chords/D/Dmaj9sus4.mp3",
    "diagram": "assets/diagrams/D/Dmaj9sus4.png"
   },
   {
    "type": "",
    "label": "Dmaj7flat5",
    "audio": "assets/audio/chords/D/Dmaj7flat5.mp3",
    "diagram": "assets/diagrams/D/Dmaj7flat5.png"
   },
   {
    "type": "",
    "label": "Dmaj7sharp5",
    "audio": "assets/audio/chords/D/Dmaj7sharp5.mp3",
    "diagram": "assets/diagrams/D/Dmaj7sharp5.png"
   }
  ]
 },
 "Eb": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "Eb",
    "audio": "assets/audio/chords/Eb/Eb.mp3",
    "diagram": "assets/diagrams/Eb/Eb.png"
   },
   {
    "type": "",
    "label": "Eb6",
    "audio": "assets/audio/chords/Eb/Eb6.mp3",
    "diagram": "assets/diagrams/Eb/Eb6.png"
   },
   {
    "type": "",
    "label": "Eb7",
    "audio": "assets/audio/chords/Eb/Eb7.mp3",
    "diagram": "assets/diagrams/Eb/Eb7.png"
   },
   {
    "type": "",
    "label": "Eb9",
    "audio": "assets/audio/chords/Eb/Eb9.mp3",
    "diagram": "assets/diagrams/Eb/Eb9.png"
   },
   {
    "type": "",
    "label": "Ebm",
    "audio": "assets/audio/chords/Eb/Ebm.mp3",
    "diagram": "assets/diagrams/Eb/Ebm.png"
   },
   {
    "type": "",
    "label": "Eb11",
    "audio": "assets/audio/chords/Eb/Eb11.mp3",
    "diagram": "assets/diagrams/Eb/Eb11.png"
   },
   {
    "type": "",
    "label": "Eb13",
    "audio": "assets/audio/chords/Eb/Eb13.mp3",
    "diagram": "assets/diagrams/Eb/Eb13.png"
   },
   {
    "type": "",
    "label": "Eb69",
    "audio": "assets/audio/chords/Eb/Eb69.mp3",
    "diagram": "assets/diagrams/Eb/Eb69.png"
   },
   {
    "type": "",
    "label": "Ebm6",
    "audio": "assets/audio/chords/Eb/Ebm6.mp3",
    "diagram": "assets/diagrams/Eb/Ebm6.png"
   },
   {
    "type": "",
    "label": "Ebm7",
    "audio": "assets/audio/chords/Eb/Ebm7.mp3",
    "diagram": "assets/diagrams/Eb/Ebm7.png"
   },
   {
    "type": "",
    "label": "Ebm9",
    "audio": "assets/audio/chords/Eb/Ebm9.mp3",
    "diagram": "assets/diagrams/Eb/Ebm9.png"
   },
   {
    "type": "",
    "label": "Ebaug",
    "audio": "assets/audio/chords/Eb/Ebaug.mp3",
    "diagram": "assets/diagrams/Eb/Ebaug.png"
   },
   {
    "type": "",
    "label": "Ebdim",
    "audio": "assets/audio/chords/Eb/Ebdim.mp3",
    "diagram": "assets/diagrams/Eb/Ebdim.png"
   },
   {
    "type": "",
    "label": "Ebm69",
    "audio": "assets/audio/chords/Eb/Ebm69.mp3",
    "diagram": "assets/diagrams/Eb/Ebm69.png"
   },
   {
    "type": "",
    "label": "Ebadd9",
    "audio": "assets/audio/chords/Eb/Ebadd9.mp3",
    "diagram": "assets/diagrams/Eb/Ebadd9.png"
   },
   {
    "type": "",
    "label": "Ebdim7",
    "audio": "assets/audio/chords/Eb/Ebdim7.mp3",
    "diagram": "assets/diagrams/Eb/Ebdim7.png"
   },
   {
    "type": "",
    "label": "Ebmaj7",
    "audio": "assets/audio/chords/Eb/Ebmaj7.mp3",
    "diagram": "assets/diagrams/Eb/EbMaj7.png"
   },
   {
    "type": "",
    "label": "Ebmaj9",
    "audio": "assets/audio/chords/Eb/Ebmaj9.mp3",
    "diagram": "assets/diagrams/Eb/EbMaj9.png"
   },
   {
    "type": "",
    "label": "Ebsus2",
    "audio": "assets/audio/chords/Eb/Ebsus2.mp3",
    "diagram": "assets/diagrams/Eb/Ebsus2.png"
   },
   {
    "type": "",
    "label": "Ebsus4",
    "audio": "assets/audio/chords/Eb/Ebsus4.mp3",
    "diagram": "assets/diagrams/Eb/Ebsus4.png"
   },
   {
    "type": "",
    "label": "Eb7sus4",
    "audio": "assets/audio/chords/Eb/Eb7sus4.mp3",
    "diagram": "assets/diagrams/Eb/Eb7sus4.png"
   },
   {
    "type": "",
    "label": "Eb9sus4",
    "audio": "assets/audio/chords/Eb/Eb9sus4.mp3",
    "diagram": "assets/diagrams/Eb/Eb9sus4.png"
   },
   {
    "type": "",
    "label": "EbmMaj7",
    "audio": "assets/audio/chords/Eb/EbmMaj7.mp3",
    "diagram": "assets/diagrams/Eb/EbmMaj7.png"
   },
   {
    "type": "",
    "label": "EbmMaj9",
    "audio": "assets/audio/chords/Eb/EbmMaj9.mp3",
    "diagram": "assets/diagrams/Eb/EbmMaj9.png"
   },
   {
    "type": "",
    "label": "Ebmadd9",
    "audio": "assets/audio/chords/Eb/Ebmadd9.mp3",
    "diagram": "assets/diagrams/Eb/Ebmadd9.png"
   },
   {
    "type": "",
    "label": "Eb7flat5",
    "audio": "assets/audio/chords/Eb/Eb7flat5.mp3",
    "diagram": "assets/diagrams/Eb/Eb7flat5.png"
   },
   {
    "type": "",
    "label": "Eb7flat9",
    "audio": "assets/audio/chords/Eb/Eb7flat9.mp3",
    "diagram": "assets/diagrams/Eb/Eb7flat9.png"
   },
   {
    "type": "",
    "label": "Eb7flat13",
    "audio": "assets/audio/chords/Eb/Eb7flat13.mp3",
    "diagram": "assets/diagrams/Eb/Eb7flat13.png"
   },
   {
    "type": "",
    "label": "Eb7sharp5",
    "audio": "assets/audio/chords/Eb/Eb7sharp5.mp3",
    "diagram": "assets/diagrams/Eb/Eb7sharp5.png"
   },
   {
    "type": "",
    "label": "Eb7sharp9",
    "audio": "assets/audio/chords/Eb/Eb7sharp9.mp3",
    "diagram": "assets/diagrams/Eb/Eb7sharp9.png"
   },
   {
    "type": "",
    "label": "Ebm7flat5",
    "audio": "assets/audio/chords/Eb/Ebm7flat5.mp3",
    "diagram": "assets/diagrams/Eb/EbMaj7flat5.png"
   },
   {
    "type": "",
    "label": "Ebmsharp5",
    "audio": "assets/audio/chords/Eb/Ebmsharp5.mp3",
    "diagram": "assets/diagrams/Eb/Ebmsharp5.png"
   },
   {
    "type": "",
    "label": "Eb7sharp11",
    "audio": "assets/audio/chords/Eb/Eb7sharp11.mp3",
    "diagram": "assets/diagrams/Eb/Eb7sharp11.png"
   },
   {
    "type": "",
    "label": "EbMaj7sus4",
    "audio": "assets/audio/chords/Eb/EbMaj7sus4.mp3",
    "diagram": "assets/diagrams/Eb/EbMaj7sus4.png"
   },
   {
    "type": "",
    "label": "EbMaj9sus4",
    "audio": "assets/audio/chords/Eb/EbMaj9sus4.mp3",
    "diagram": "assets/diagrams/Eb/EbMaj9sus4.png"
   },
   {
    "type": "",
    "label": "Ebm7sharp5",
    "audio": "assets/audio/chords/Eb/Ebm7sharp5.mp3",
    "diagram": "assets/diagrams/Eb/Ebm7sharp5.png"
   },
   {
    "type": "",
    "label": "Ebmaj7flat5",
    "audio": "assets/audio/chords/Eb/Ebmaj7flat5.mp3",
    "diagram": "assets/diagrams/Eb/EbMaj7flat5.png"
   },
   {
    "type": "",
    "label": "Ebmaj7sharp5",
    "audio": "assets/audio/chords/Eb/Ebmaj7sharp5.mp3",
    "diagram": "assets/diagrams/Eb/EbMaj7sharp5.png"
   }
  ]
 },
 "E": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "E",
    "audio": "assets/audio/chords/E/E.mp3",
    "diagram": "assets/diagrams/E/E.png"
   },
   {
    "type": "",
    "label": "E6",
    "audio": "assets/audio/chords/E/E6.mp3",
    "diagram": "assets/diagrams/E/E6.png"
   },
   {
    "type": "",
    "label": "E7",
    "audio": "assets/audio/chords/E/E7.mp3",
    "diagram": "assets/diagrams/E/E7.png"
   },
   {
    "type": "",
    "label": "E9",
    "audio": "assets/audio/chords/E/E9.mp3",
    "diagram": "assets/diagrams/E/E9.png"
   },
   {
    "type": "",
    "label": "Em",
    "audio": "assets/audio/chords/E/Em.mp3",
    "diagram": "assets/diagrams/E/Em.png"
   },
   {
    "type": "",
    "label": "E11",
    "audio": "assets/audio/chords/E/E11.mp3",
    "diagram": "assets/diagrams/E/E11.png"
   },
   {
    "type": "",
    "label": "E13",
    "audio": "assets/audio/chords/E/E13.mp3",
    "diagram": "assets/diagrams/E/E13.png"
   },
   {
    "type": "",
    "label": "E69",
    "audio": "assets/audio/chords/E/E69.mp3",
    "diagram": "assets/diagrams/E/E69.png"
   },
   {
    "type": "",
    "label": "Em6",
    "audio": "assets/audio/chords/E/Em6.mp3",
    "diagram": "assets/diagrams/E/Em6.png"
   },
   {
    "type": "",
    "label": "Em7",
    "audio": "assets/audio/chords/E/Em7.mp3",
    "diagram": "assets/diagrams/E/Em7.png"
   },
   {
    "type": "",
    "label": "Em9",
    "audio": "assets/audio/chords/E/Em9.mp3",
    "diagram": "assets/diagrams/E/Em9.png"
   },
   {
    "type": "",
    "label": "Eaug",
    "audio": "assets/audio/chords/E/Eaug.mp3",
    "diagram": "assets/diagrams/E/Eaug.png"
   },
   {
    "type": "",
    "label": "Edim",
    "audio": "assets/audio/chords/E/Edim.mp3",
    "diagram": "assets/diagrams/E/Edim.png"
   },
   {
    "type": "",
    "label": "Em69",
    "audio": "assets/audio/chords/E/Em69.mp3",
    "diagram": "assets/diagrams/E/Em69.png"
   },
   {
    "type": "",
    "label": "Eadd9",
    "audio": "assets/audio/chords/E/Eadd9.mp3",
    "diagram": "assets/diagrams/E/Eadd9.png"
   },
   {
    "type": "",
    "label": "Edim7",
    "audio": "assets/audio/chords/E/Edim7.mp3",
    "diagram": "assets/diagrams/E/Edim7.png"
   },
   {
    "type": "",
    "label": "Emaj7",
    "audio": "assets/audio/chords/E/Emaj7.mp3",
    "diagram": "assets/diagrams/E/Emaj7.png"
   },
   {
    "type": "",
    "label": "Emaj9",
    "audio": "assets/audio/chords/E/Emaj9.mp3",
    "diagram": "assets/diagrams/E/Emaj9.png"
   },
   {
    "type": "",
    "label": "Esus2",
    "audio": "assets/audio/chords/E/Esus2.mp3",
    "diagram": "assets/diagrams/E/Esus2.png"
   },
   {
    "type": "",
    "label": "Esus4",
    "audio": "assets/audio/chords/E/Esus4.mp3",
    "diagram": "assets/diagrams/E/Esus4.png"
   },
   {
    "type": "",
    "label": "E7sus4",
    "audio": "assets/audio/chords/E/E7sus4.mp3",
    "diagram": "assets/diagrams/E/E7sus4.png"
   },
   {
    "type": "",
    "label": "E9sus4",
    "audio": "assets/audio/chords/E/E9sus4.mp3",
    "diagram": "assets/diagrams/E/E9sus4.png"
   },
   {
    "type": "",
    "label": "EmMaj7",
    "audio": "assets/audio/chords/E/EmMaj7.mp3",
    "diagram": "assets/diagrams/E/EmMaj7.png"
   },
   {
    "type": "",
    "label": "EmMaj9",
    "audio": "assets/audio/chords/E/EmMaj9.mp3",
    "diagram": "assets/diagrams/E/EmMaj9.png"
   },
   {
    "type": "",
    "label": "Emadd9",
    "audio": "assets/audio/chords/E/Emadd9.mp3",
    "diagram": "assets/diagrams/E/Emadd9.png"
   },
   {
    "type": "",
    "label": "E7flat5",
    "audio": "assets/audio/chords/E/E7flat5.mp3",
    "diagram": "assets/diagrams/E/E7flat5.png"
   },
   {
    "type": "",
    "label": "E7flat9",
    "audio": "assets/audio/chords/E/E7flat9.mp3",
    "diagram": "assets/diagrams/E/E7flat9.png"
   },
   {
    "type": "",
    "label": "E7flat13",
    "audio": "assets/audio/chords/E/E7flat13.mp3",
    "diagram": "assets/diagrams/E/E7flat13.png"
   },
   {
    "type": "",
    "label": "E7sharp5",
    "audio": "assets/audio/chords/E/E7sharp5.mp3",
    "diagram": "assets/diagrams/E/E7sharp5.png"
   },
   {
    "type": "",
    "label": "E7sharp9",
    "audio": "assets/audio/chords/E/E7sharp9.mp3",
    "diagram": "assets/diagrams/E/E7sharp9.png"
   },
   {
    "type": "",
    "label": "Em7flat5",
    "audio": "assets/audio/chords/E/Em7flat5.mp3",
    "diagram": "assets/diagrams/E/Em7flat5.png"
   },
   {
    "type": "",
    "label": "Emsharp5",
    "audio": "assets/audio/chords/E/Emsharp5.mp3",
    "diagram": "assets/diagrams/E/Emsharp5.png"
   },
   {
    "type": "",
    "label": "E7sharp11",
    "audio": "assets/audio/chords/E/E7sharp11.mp3",
    "diagram": "assets/diagrams/E/E7sharp11.png"
   },
   {
    "type": "",
    "label": "EMaj7sus4",
    "audio": "assets/audio/chords/E/EMaj7sus4.mp3",
    "diagram": "assets/diagrams/E/EMaj7sus4.png"
   },
   {
    "type": "",
    "label": "Em7sharp5",
    "audio": "assets/audio/chords/E/Em7sharp5.mp3",
    "diagram": "assets/diagrams/E/Em7sharp5.png"
   },
   {
    "type": "",
    "label": "Emaj9sus4",
    "audio": "assets/audio/chords/E/Emaj9sus4.mp3",
    "diagram": "assets/diagrams/E/Emaj9sus4.png"
   },
   {
    "type": "",
    "label": "Emaj7flat5",
    "audio": "assets/audio/chords/E/Emaj7flat5.mp3",
    "diagram": "assets/diagrams/E/Emaj7flat5.png"
   },
   {
    "type": "",
    "label": "Emaj7sharp5",
    "audio": "assets/audio/chords/E/Emaj7sharp5.mp3",
    "diagram": "assets/diagrams/E/Emaj7sharp5.png"
   }
  ]
 },
 "F": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "F",
    "audio": "assets/audio/chords/F/F.mp3",
    "diagram": "assets/diagrams/F/F.png"
   },
   {
    "type": "",
    "label": "F6",
    "audio": "assets/audio/chords/F/F6.mp3",
    "diagram": "assets/diagrams/F/F6.png"
   },
   {
    "type": "",
    "label": "F7",
    "audio": "assets/audio/chords/F/F7.mp3",
    "diagram": "assets/diagrams/F/F7.png"
   },
   {
    "type": "",
    "label": "F9",
    "audio": "assets/audio/chords/F/F9.mp3",
    "diagram": "assets/diagrams/F/F9.png"
   },
   {
    "type": "",
    "label": "Fm",
    "audio": "assets/audio/chords/F/Fm.mp3",
    "diagram": "assets/diagrams/F/Fm.png"
   },
   {
    "type": "",
    "label": "F11",
    "audio": "assets/audio/chords/F/F11.mp3",
    "diagram": "assets/diagrams/F/F11.png"
   },
   {
    "type": "",
    "label": "F13",
    "audio": "assets/audio/chords/F/F13.mp3",
    "diagram": "assets/diagrams/F/F13.png"
   },
   {
    "type": "",
    "label": "F69",
    "audio": "assets/audio/chords/F/F69.mp3",
    "diagram": "assets/diagrams/F/F69.png"
   },
   {
    "type": "",
    "label": "Fm6",
    "audio": "assets/audio/chords/F/Fm6.mp3",
    "diagram": "assets/diagrams/F/Fm6.png"
   },
   {
    "type": "",
    "label": "Fm7",
    "audio": "assets/audio/chords/F/Fm7.mp3",
    "diagram": "assets/diagrams/F/FMaj7.png"
   },
   {
    "type": "",
    "label": "Fm9",
    "audio": "assets/audio/chords/F/Fm9.mp3",
    "diagram": "assets/diagrams/F/Fm9.png"
   },
   {
    "type": "",
    "label": "Faug",
    "audio": "assets/audio/chords/F/Faug.mp3",
    "diagram": "assets/diagrams/F/Faug.png"
   },
   {
    "type": "",
    "label": "Fdim",
    "audio": "assets/audio/chords/F/Fdim.mp3",
    "diagram": "assets/diagrams/F/Fdim.png"
   },
   {
    "type": "",
    "label": "Fm69",
    "audio": "assets/audio/chords/F/Fm69.mp3",
    "diagram": "assets/diagrams/F/Fm69.png"
   },
   {
    "type": "",
    "label": "Fadd9",
    "audio": "assets/audio/chords/F/Fadd9.mp3",
    "diagram": "assets/diagrams/F/Fadd9.png"
   },
   {
    "type": "",
    "label": "Fdim7",
    "audio": "assets/audio/chords/F/Fdim7.mp3",
    "diagram": "assets/diagrams/F/Fdim7.png"
   },
   {
    "type": "",
    "label": "Fmaj7",
    "audio": "assets/audio/chords/F/Fmaj7.mp3",
    "diagram": "assets/diagrams/F/FMaj7.png"
   },
   {
    "type": "",
    "label": "Fmaj9",
    "audio": "assets/audio/chords/F/Fmaj9.mp3",
    "diagram": "assets/diagrams/F/Fmaj9.png"
   },
   {
    "type": "",
    "label": "Fsus2",
    "audio": "assets/audio/chords/F/Fsus2.mp3",
    "diagram": "assets/diagrams/F/Fsus2.png"
   },
   {
    "type": "",
    "label": "Fsus4",
    "audio": "assets/audio/chords/F/Fsus4.mp3",
    "diagram": "assets/diagrams/F/Fsus4.png"
   },
   {
    "type": "",
    "label": "F7sus4",
    "audio": "assets/audio/chords/F/F7sus4.mp3",
    "diagram": "assets/diagrams/F/F7sus4.png"
   },
   {
    "type": "",
    "label": "F9sus4",
    "audio": "assets/audio/chords/F/F9sus4.mp3",
    "diagram": "assets/diagrams/F/F9sus4.png"
   },
   {
    "type": "",
    "label": "FmMaj7",
    "audio": "assets/audio/chords/F/FmMaj7.mp3",
    "diagram": "assets/diagrams/F/FmMaj7.png"
   },
   {
    "type": "",
    "label": "FmMaj9",
    "audio": "assets/audio/chords/F/FmMaj9.mp3",
    "diagram": "assets/diagrams/F/FmMaj9.png"
   },
   {
    "type": "",
    "label": "Fmadd9",
    "audio": "assets/audio/chords/F/Fmadd9.mp3",
    "diagram": "assets/diagrams/F/Fmadd9.png"
   },
   {
    "type": "",
    "label": "F7flat5",
    "audio": "assets/audio/chords/F/F7flat5.mp3",
    "diagram": "assets/diagrams/F/F7flat5.png"
   },
   {
    "type": "",
    "label": "F7flat9",
    "audio": "assets/audio/chords/F/F7flat9.mp3",
    "diagram": "assets/diagrams/F/F7flat9.png"
   },
   {
    "type": "",
    "label": "F7flat13",
    "audio": "assets/audio/chords/F/F7flat13.mp3",
    "diagram": "assets/diagrams/F/F7flat13.png"
   },
   {
    "type": "",
    "label": "F7sharp5",
    "audio": "assets/audio/chords/F/F7sharp5.mp3",
    "diagram": "assets/diagrams/F/F7sharp5.png"
   },
   {
    "type": "",
    "label": "F7sharp9",
    "audio": "assets/audio/chords/F/F7sharp9.mp3",
    "diagram": "assets/diagrams/F/F7sharp9.png"
   },
   {
    "type": "",
    "label": "Fm7flat5",
    "audio": "assets/audio/chords/F/Fm7flat5.mp3",
    "diagram": "assets/diagrams/F/Fm7flat5.png"
   },
   {
    "type": "",
    "label": "Fmsharp5",
    "audio": "assets/audio/chords/F/Fmsharp5.mp3",
    "diagram": "assets/diagrams/F/Fmsharp5.png"
   },
   {
    "type": "",
    "label": "F7sharp11",
    "audio": "assets/audio/chords/F/F7sharp11.mp3",
    "diagram": "assets/diagrams/F/F7sharp11.png"
   },
   {
    "type": "",
    "label": "FMaj7sus4",
    "audio": "assets/audio/chords/F/FMaj7sus4.mp3",
    "diagram": "assets/diagrams/F/FMaj7sus4.png"
   },
   {
    "type": "",
    "label": "Fm7sharp5",
    "audio": "assets/audio/chords/F/Fm7sharp5.mp3",
    "diagram": "assets/diagrams/F/Fm7sharp5.png"
   },
   {
    "type": "",
    "label": "Fmaj9sus4",
    "audio": "assets/audio/chords/F/Fmaj9sus4.mp3",
    "diagram": "assets/diagrams/F/FMaj9sus4.png"
   },
   {
    "type": "",
    "label": "Fmaj7flat5",
    "audio": "assets/audio/chords/F/Fmaj7flat5.mp3",
    "diagram": "assets/diagrams/F/Fmaj7flat5.png"
   },
   {
    "type": "",
    "label": "Fmaj7sharp5",
    "audio": "assets/audio/chords/F/Fmaj7sharp5.mp3",
    "diagram": "assets/diagrams/F/FMaj7sharp5.png"
   }
  ]
 },
 "Gb": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "Gb",
    "audio": "assets/audio/chords/Gb/Gb.mp3",
    "diagram": "assets/diagrams/Gb/Gb.png"
   },
   {
    "type": "",
    "label": "Gb6",
    "audio": "assets/audio/chords/Gb/Gb6.mp3",
    "diagram": "assets/diagrams/Gb/Gb6.png"
   },
   {
    "type": "",
    "label": "Gb7",
    "audio": "assets/audio/chords/Gb/Gb7.mp3",
    "diagram": "assets/diagrams/Gb/Gb7.png"
   },
   {
    "type": "",
    "label": "Gb9",
    "audio": "assets/audio/chords/Gb/Gb9.mp3",
    "diagram": "assets/diagrams/Gb/Gb9.png"
   },
   {
    "type": "",
    "label": "Gbm",
    "audio": "assets/audio/chords/Gb/Gbm.mp3",
    "diagram": "assets/diagrams/Gb/Gbm.png"
   },
   {
    "type": "",
    "label": "Gb11",
    "audio": "assets/audio/chords/Gb/Gb11.mp3",
    "diagram": "assets/diagrams/Gb/Gb11.png"
   },
   {
    "type": "",
    "label": "Gb13",
    "audio": "assets/audio/chords/Gb/Gb13.mp3",
    "diagram": "assets/diagrams/Gb/Gb13.png"
   },
   {
    "type": "",
    "label": "Gb69",
    "audio": "assets/audio/chords/Gb/Gb69.mp3",
    "diagram": "assets/diagrams/Gb/Gb69.png"
   },
   {
    "type": "",
    "label": "Gbm6",
    "audio": "assets/audio/chords/Gb/Gbm6.mp3",
    "diagram": "assets/diagrams/Gb/Gbm6.png"
   },
   {
    "type": "",
    "label": "Gbm7",
    "audio": "assets/audio/chords/Gb/Gbm7.mp3",
    "diagram": "assets/diagrams/Gb/GbMaj7.png"
   },
   {
    "type": "",
    "label": "Gbm9",
    "audio": "assets/audio/chords/Gb/Gbm9.mp3",
    "diagram": "assets/diagrams/Gb/Gbm9.png"
   },
   {
    "type": "",
    "label": "Gbaug",
    "audio": "assets/audio/chords/Gb/Gbaug.mp3",
    "diagram": "assets/diagrams/Gb/Gbaug.png"
   },
   {
    "type": "",
    "label": "Gbdim",
    "audio": "assets/audio/chords/Gb/Gbdim.mp3",
    "diagram": "assets/diagrams/Gb/Gbdim.png"
   },
   {
    "type": "",
    "label": "Gbm69",
    "audio": "assets/audio/chords/Gb/Gbm69.mp3",
    "diagram": "assets/diagrams/Gb/Gbm69.png"
   },
   {
    "type": "",
    "label": "Gbadd9",
    "audio": "assets/audio/chords/Gb/Gbadd9.mp3",
    "diagram": "assets/diagrams/Gb/Gbadd9.png"
   },
   {
    "type": "",
    "label": "Gbdim7",
    "audio": "assets/audio/chords/Gb/Gbdim7.mp3",
    "diagram": "assets/diagrams/Gb/Gbdim7.png"
   },
   {
    "type": "",
    "label": "Gbmaj7",
    "audio": "assets/audio/chords/Gb/Gbmaj7.mp3",
    "diagram": "assets/diagrams/Gb/GbMaj7.png"
   },
   {
    "type": "",
    "label": "Gbmaj9",
    "audio": "assets/audio/chords/Gb/Gbmaj9.mp3",
    "diagram": "assets/diagrams/Gb/Gbmaj9.png"
   },
   {
    "type": "",
    "label": "Gbsus2",
    "audio": "assets/audio/chords/Gb/Gbsus2.mp3",
    "diagram": "assets/diagrams/Gb/Gbsus2.png"
   },
   {
    "type": "",
    "label": "Gbsus4",
    "audio": "assets/audio/chords/Gb/Gbsus4.mp3",
    "diagram": "assets/diagrams/Gb/Gbsus4.png"
   },
   {
    "type": "",
    "label": "Gb7sus4",
    "audio": "assets/audio/chords/Gb/Gb7sus4.mp3",
    "diagram": "assets/diagrams/Gb/Gb7sus4.png"
   },
   {
    "type": "",
    "label": "Gb9sus4",
    "audio": "assets/audio/chords/Gb/Gb9sus4.mp3",
    "diagram": "assets/diagrams/Gb/Gb9sus4.png"
   },
   {
    "type": "",
    "label": "GbmMaj7",
    "audio": "assets/audio/chords/Gb/GbmMaj7.mp3",
    "diagram": "assets/diagrams/Gb/GbmMaj7.png"
   },
   {
    "type": "",
    "label": "GbmMaj9",
    "audio": "assets/audio/chords/Gb/GbmMaj9.mp3",
    "diagram": "assets/diagrams/Gb/GbmMaj9.png"
   },
   {
    "type": "",
    "label": "Gbmadd9",
    "audio": "assets/audio/chords/Gb/Gbmadd9.mp3",
    "diagram": "assets/diagrams/Gb/Gbmadd9.png"
   },
   {
    "type": "",
    "label": "Gb7flat5",
    "audio": "assets/audio/chords/Gb/Gb7flat5.mp3",
    "diagram": "assets/diagrams/Gb/Gb7flat5.png"
   },
   {
    "type": "",
    "label": "Gb7flat9",
    "audio": "assets/audio/chords/Gb/Gb7flat9.mp3",
    "diagram": "assets/diagrams/Gb/Gb7flat9.png"
   },
   {
    "type": "",
    "label": "Gb7flat13",
    "audio": "assets/audio/chords/Gb/Gb7flat13.mp3",
    "diagram": "assets/diagrams/Gb/Gb7flat13.png"
   },
   {
    "type": "",
    "label": "Gb7sharp5",
    "audio": "assets/audio/chords/Gb/Gb7sharp5.mp3",
    "diagram": "assets/diagrams/Gb/Gb7sharp5.png"
   },
   {
    "type": "",
    "label": "Gb7sharp9",
    "audio": "assets/audio/chords/Gb/Gb7sharp9.mp3",
    "diagram": "assets/diagrams/Gb/Gb7sharp9.png"
   },
   {
    "type": "",
    "label": "Gbm7flat5",
    "audio": "assets/audio/chords/Gb/Gbm7flat5.mp3",
    "diagram": "assets/diagrams/Gb/Gbm7flat5.png"
   },
   {
    "type": "",
    "label": "Gbmsharp5",
    "audio": "assets/audio/chords/Gb/Gbmsharp5.mp3",
    "diagram": "assets/diagrams/Gb/Gbmsharp5.png"
   },
   {
    "type": "",
    "label": "Gb7sharp11",
    "audio": "assets/audio/chords/Gb/Gb7sharp11.mp3",
    "diagram": "assets/diagrams/Gb/Gb7sharp11.png"
   },
   {
    "type": "",
    "label": "GbMaj7sus4",
    "audio": "assets/audio/chords/Gb/GbMaj7sus4.mp3",
    "diagram": "assets/diagrams/Gb/GbMaj7sus4.png"
   },
   {
    "type": "",
    "label": "GbMaj9sus4",
    "audio": "assets/audio/chords/Gb/GbMaj9sus4.mp3",
    "diagram": "assets/diagrams/Gb/GbMaj9sus4.png"
   },
   {
    "type": "",
    "label": "Gbm7sharp5",
    "audio": "assets/audio/chords/Gb/Gbm7sharp5.mp3",
    "diagram": "assets/diagrams/Gb/Gbm7sharp5.png"
   },
   {
    "type": "",
    "label": "Gbmaj7flat5",
    "audio": "assets/audio/chords/Gb/Gbmaj7flat5.mp3",
    "diagram": "assets/diagrams/Gb/Gbmaj7flat5.png"
   },
   {
    "type": "",
    "label": "Gbmaj7sharp5",
    "audio": "assets/audio/chords/Gb/Gbmaj7sharp5.mp3",
    "diagram": "assets/diagrams/Gb/Gbmaj7sharp5.png"
   }
  ]
 },
 "G": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "G",
    "audio": "assets/audio/chords/G/G.mp3",
    "diagram": "assets/diagrams/G/G.png"
   },
   {
    "type": "",
    "label": "G6",
    "audio": "assets/audio/chords/G/G6.mp3",
    "diagram": "assets/diagrams/G/G6.png"
   },
   {
    "type": "",
    "label": "G7",
    "audio": "assets/audio/chords/G/G7.mp3",
    "diagram": "assets/diagrams/G/G7.png"
   },
   {
    "type": "",
    "label": "G9",
    "audio": "assets/audio/chords/G/G9.mp3",
    "diagram": "assets/diagrams/G/G9.png"
   },
   {
    "type": "",
    "label": "Gm",
    "audio": "assets/audio/chords/G/Gm.mp3",
    "diagram": "assets/diagrams/G/Gm.png"
   },
   {
    "type": "",
    "label": "G11",
    "audio": "assets/audio/chords/G/G11.mp3",
    "diagram": "assets/diagrams/G/G11.png"
   },
   {
    "type": "",
    "label": "G13",
    "audio": "assets/audio/chords/G/G13.mp3",
    "diagram": "assets/diagrams/G/G13.png"
   },
   {
    "type": "",
    "label": "G69",
    "audio": "assets/audio/chords/G/G69.mp3",
    "diagram": "assets/diagrams/G/G69.png"
   },
   {
    "type": "",
    "label": "Gm6",
    "audio": "assets/audio/chords/G/Gm6.mp3",
    "diagram": "assets/diagrams/G/Gm6.png"
   },
   {
    "type": "",
    "label": "Gm7",
    "audio": "assets/audio/chords/G/Gm7.mp3",
    "diagram": "assets/diagrams/G/Gm7.png"
   },
   {
    "type": "",
    "label": "Gm9",
    "audio": "assets/audio/chords/G/Gm9.mp3",
    "diagram": "assets/diagrams/G/Gm9.png"
   },
   {
    "type": "",
    "label": "GAug",
    "audio": "assets/audio/chords/G/GAug.mp3",
    "diagram": "assets/diagrams/G/Gaug.png"
   },
   {
    "type": "",
    "label": "Gdim",
    "audio": "assets/audio/chords/G/Gdim.mp3",
    "diagram": "assets/diagrams/G/Gdim.png"
   },
   {
    "type": "",
    "label": "Gm69",
    "audio": "assets/audio/chords/G/Gm69.mp3",
    "diagram": "assets/diagrams/G/Gm69.png"
   },
   {
    "type": "",
    "label": "Gadd9",
    "audio": "assets/audio/chords/G/Gadd9.mp3",
    "diagram": "assets/diagrams/G/Gadd9.png"
   },
   {
    "type": "",
    "label": "Gdim7",
    "audio": "assets/audio/chords/G/Gdim7.mp3",
    "diagram": "assets/diagrams/G/Gdim7.png"
   },
   {
    "type": "",
    "label": "Gmaj7",
    "audio": "assets/audio/chords/G/Gmaj7.mp3",
    "diagram": "assets/diagrams/G/Gmaj7.png"
   },
   {
    "type": "",
    "label": "Gmaj9",
    "audio": "assets/audio/chords/G/Gmaj9.mp3",
    "diagram": "assets/diagrams/G/Gmaj9.png"
   },
   {
    "type": "",
    "label": "Gsus2",
    "audio": "assets/audio/chords/G/Gsus2.mp3",
    "diagram": "assets/diagrams/G/Gsus2.png"
   },
   {
    "type": "",
    "label": "Gsus4",
    "audio": "assets/audio/chords/G/Gsus4.mp3",
    "diagram": "assets/diagrams/G/Gsus4.png"
   },
   {
    "type": "",
    "label": "G7sus4",
    "audio": "assets/audio/chords/G/G7sus4.mp3",
    "diagram": "assets/diagrams/G/G7sus4.png"
   },
   {
    "type": "",
    "label": "G9sus4",
    "audio": "assets/audio/chords/G/G9sus4.mp3",
    "diagram": "assets/diagrams/G/G9sus4.png"
   },
   {
    "type": "",
    "label": "GmMaj7",
    "audio": "assets/audio/chords/G/GmMaj7.mp3",
    "diagram": "assets/diagrams/G/GmMaj7.png"
   },
   {
    "type": "",
    "label": "GmMaj9",
    "audio": "assets/audio/chords/G/GmMaj9.mp3",
    "diagram": "assets/diagrams/G/GmMaj9.png"
   },
   {
    "type": "",
    "label": "Gmadd9",
    "audio": "assets/audio/chords/G/Gmadd9.mp3",
    "diagram": "assets/diagrams/G/Gmadd9.png"
   },
   {
    "type": "",
    "label": "G7flat5",
    "audio": "assets/audio/chords/G/G7flat5.mp3",
    "diagram": "assets/diagrams/G/G7flat5.png"
   },
   {
    "type": "",
    "label": "G7flat9",
    "audio": "assets/audio/chords/G/G7flat9.mp3",
    "diagram": "assets/diagrams/G/G7flat9.png"
   },
   {
    "type": "",
    "label": "G7flat13",
    "audio": "assets/audio/chords/G/G7flat13.mp3",
    "diagram": "assets/diagrams/G/G7flat13.png"
   },
   {
    "type": "",
    "label": "G7sharp5",
    "audio": "assets/audio/chords/G/G7sharp5.mp3",
    "diagram": "assets/diagrams/G/G7sharp5.png"
   },
   {
    "type": "",
    "label": "G7sharp9",
    "audio": "assets/audio/chords/G/G7sharp9.mp3",
    "diagram": "assets/diagrams/G/G7sharp9.png"
   },
   {
    "type": "",
    "label": "Gm7flat5",
    "audio": "assets/audio/chords/G/Gm7flat5.mp3",
    "diagram": "assets/diagrams/G/Gm7flat5.png"
   },
   {
    "type": "",
    "label": "Gmsharp5",
    "audio": "assets/audio/chords/G/Gmsharp5.mp3",
    "diagram": "assets/diagrams/G/Gmsharp5.png"
   },
   {
    "type": "",
    "label": "G7sharp11",
    "audio": "assets/audio/chords/G/G7sharp11.mp3",
    "diagram": "assets/diagrams/G/G7sharp11.png"
   },
   {
    "type": "",
    "label": "GMaj7sus4",
    "audio": "assets/audio/chords/G/GMaj7sus4.mp3",
    "diagram": "assets/diagrams/G/GMaj7sus4.png"
   },
   {
    "type": "",
    "label": "GMaj9sus4",
    "audio": "assets/audio/chords/G/GMaj9sus4.mp3",
    "diagram": "assets/diagrams/G/Gmaj9sus4.png"
   },
   {
    "type": "",
    "label": "Gm7sharp5",
    "audio": "assets/audio/chords/G/Gm7sharp5.mp3",
    "diagram": "assets/diagrams/G/Gm7sharp5.png"
   },
   {
    "type": "",
    "label": "Gmaj7flat5",
    "audio": "assets/audio/chords/G/Gmaj7flat5.mp3",
    "diagram": "assets/diagrams/G/Gmaj7flat5.png"
   },
   {
    "type": "",
    "label": "Gmaj7sharp5",
    "audio": "assets/audio/chords/G/Gmaj7sharp5.mp3",
    "diagram": "assets/diagrams/G/Gmaj7sharp5.png"
   }
  ]
 },
 "Ab": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "Ab",
    "audio": "assets/audio/chords/Ab/Ab.mp3",
    "diagram": "assets/diagrams/Ab/Ab.png"
   },
   {
    "type": "",
    "label": "Ab6",
    "audio": "assets/audio/chords/Ab/Ab6.mp3",
    "diagram": "assets/diagrams/Ab/Ab6.png"
   },
   {
    "type": "",
    "label": "Ab7",
    "audio": "assets/audio/chords/Ab/Ab7.mp3",
    "diagram": "assets/diagrams/Ab/Ab7.png"
   },
   {
    "type": "",
    "label": "Ab9",
    "audio": "assets/audio/chords/Ab/Ab9.mp3",
    "diagram": "assets/diagrams/Ab/Ab9.png"
   },
   {
    "type": "",
    "label": "Abm",
    "audio": "assets/audio/chords/Ab/Abm.mp3",
    "diagram": "assets/diagrams/Ab/Abm.png"
   },
   {
    "type": "",
    "label": "Ab11",
    "audio": "assets/audio/chords/Ab/Ab11.mp3",
    "diagram": "assets/diagrams/Ab/Ab11.png"
   },
   {
    "type": "",
    "label": "Ab13",
    "audio": "assets/audio/chords/Ab/Ab13.mp3",
    "diagram": "assets/diagrams/Ab/Ab13.png"
   },
   {
    "type": "",
    "label": "Ab69",
    "audio": "assets/audio/chords/Ab/Ab69.mp3",
    "diagram": "assets/diagrams/Ab/Ab69.png"
   },
   {
    "type": "",
    "label": "Abm6",
    "audio": "assets/audio/chords/Ab/Abm6.mp3",
    "diagram": "assets/diagrams/Ab/Abm6.png"
   },
   {
    "type": "",
    "label": "Abm7",
    "audio": "assets/audio/chords/Ab/Abm7.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj7.png"
   },
   {
    "type": "",
    "label": "Abm9",
    "audio": "assets/audio/chords/Ab/Abm9.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj9.png"
   },
   {
    "type": "",
    "label": "Abaug",
    "audio": "assets/audio/chords/Ab/Abaug.mp3",
    "diagram": "assets/diagrams/Ab/Abaug.png"
   },
   {
    "type": "",
    "label": "Abdim",
    "audio": "assets/audio/chords/Ab/Abdim.mp3",
    "diagram": "assets/diagrams/Ab/Abdim.png"
   },
   {
    "type": "",
    "label": "Abm69",
    "audio": "assets/audio/chords/Ab/Abm69.mp3",
    "diagram": "assets/diagrams/Ab/Abm69.png"
   },
   {
    "type": "",
    "label": "Abadd9",
    "audio": "assets/audio/chords/Ab/Abadd9.mp3",
    "diagram": "assets/diagrams/Ab/Abadd9.png"
   },
   {
    "type": "",
    "label": "Abdim7",
    "audio": "assets/audio/chords/Ab/Abdim7.mp3",
    "diagram": "assets/diagrams/Ab/Abdim7.png"
   },
   {
    "type": "",
    "label": "Abmaj7",
    "audio": "assets/audio/chords/Ab/Abmaj7.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj7.png"
   },
   {
    "type": "",
    "label": "Abmaj9",
    "audio": "assets/audio/chords/Ab/Abmaj9.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj9.png"
   },
   {
    "type": "",
    "label": "Absus2",
    "audio": "assets/audio/chords/Ab/Absus2.mp3",
    "diagram": "assets/diagrams/Ab/Absus2.png"
   },
   {
    "type": "",
    "label": "Absus4",
    "audio": "assets/audio/chords/Ab/Absus4.mp3",
    "diagram": "assets/diagrams/Ab/Absus4.png"
   },
   {
    "type": "",
    "label": "Ab7sus4",
    "audio": "assets/audio/chords/Ab/Ab7sus4.mp3",
    "diagram": "assets/diagrams/Ab/Ab7sus4.png"
   },
   {
    "type": "",
    "label": "Ab9sus4",
    "audio": "assets/audio/chords/Ab/Ab9sus4.mp3",
    "diagram": "assets/diagrams/Ab/Ab9sus4.png"
   },
   {
    "type": "",
    "label": "AbmMaj7",
    "audio": "assets/audio/chords/Ab/AbmMaj7.mp3",
    "diagram": "assets/diagrams/Ab/AbmMaj7.png"
   },
   {
    "type": "",
    "label": "AbmMaj9",
    "audio": "assets/audio/chords/Ab/AbmMaj9.mp3",
    "diagram": "assets/diagrams/Ab/AbmMaj9.png"
   },
   {
    "type": "",
    "label": "Abmadd9",
    "audio": "assets/audio/chords/Ab/Abmadd9.mp3",
    "diagram": "assets/diagrams/Ab/Abmadd9.png"
   },
   {
    "type": "",
    "label": "Ab7flat5",
    "audio": "assets/audio/chords/Ab/Ab7flat5.mp3",
    "diagram": "assets/diagrams/Ab/Ab7flat5.png"
   },
   {
    "type": "",
    "label": "Ab7flat9",
    "audio": "assets/audio/chords/Ab/Ab7flat9.mp3",
    "diagram": "assets/diagrams/Ab/Ab7flat9.png"
   },
   {
    "type": "",
    "label": "Ab7flat13",
    "audio": "assets/audio/chords/Ab/Ab7flat13.mp3",
    "diagram": "assets/diagrams/Ab/Ab7flat13.png"
   },
   {
    "type": "",
    "label": "Ab7sharp5",
    "audio": "assets/audio/chords/Ab/Ab7sharp5.mp3",
    "diagram": "assets/diagrams/Ab/Ab7sharp5.png"
   },
   {
    "type": "",
    "label": "Ab7sharp9",
    "audio": "assets/audio/chords/Ab/Ab7sharp9.mp3",
    "diagram": "assets/diagrams/Ab/Ab7sharp9.png"
   },
   {
    "type": "",
    "label": "Abm7flat5",
    "audio": "assets/audio/chords/Ab/Abm7flat5.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj7flat5.png"
   },
   {
    "type": "",
    "label": "Abmsharp5",
    "audio": "assets/audio/chords/Ab/Abmsharp5.mp3",
    "diagram": "assets/diagrams/Ab/Abmsharp5.png"
   },
   {
    "type": "",
    "label": "Ab7sharp11",
    "audio": "assets/audio/chords/Ab/Ab7sharp11.mp3",
    "diagram": "assets/diagrams/Ab/Ab7sharp11.png"
   },
   {
    "type": "",
    "label": "AbMaj7sus4",
    "audio": "assets/audio/chords/Ab/AbMaj7sus4.mp3",
    "diagram": "assets/diagrams/Ab/AbM7sus4.png"
   },
   {
    "type": "",
    "label": "AbMaj9sus4",
    "audio": "assets/audio/chords/Ab/AbMaj9sus4.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj9sus4.png"
   },
   {
    "type": "",
    "label": "Abm7sharp5",
    "audio": "assets/audio/chords/Ab/Abm7sharp5.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj7sharp5.png"
   },
   {
    "type": "",
    "label": "Abmaj7flat5",
    "audio": "assets/audio/chords/Ab/Abmaj7flat5.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj7flat5.png"
   },
   {
    "type": "",
    "label": "Abmaj7sharp5",
    "audio": "assets/audio/chords/Ab/Abmaj7sharp5.mp3",
    "diagram": "assets/diagrams/Ab/AbMaj7sharp5.png"
   }
  ]
 },
 "A": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "A",
    "audio": "assets/audio/chords/A/A.mp3",
    "diagram": "assets/diagrams/A/A.png"
   },
   {
    "type": "",
    "label": "A6",
    "audio": "assets/audio/chords/A/A6.mp3",
    "diagram": "assets/diagrams/A/A6.png"
   },
   {
    "type": "",
    "label": "A7",
    "audio": "assets/audio/chords/A/A7.mp3",
    "diagram": "assets/diagrams/A/A7.png"
   },
   {
    "type": "",
    "label": "A9",
    "audio": "assets/audio/chords/A/A9.mp3",
    "diagram": "assets/diagrams/A/A9.png"
   },
   {
    "type": "",
    "label": "Am",
    "audio": "assets/audio/chords/A/Am.mp3",
    "diagram": "assets/diagrams/A/Am.png"
   },
   {
    "type": "",
    "label": "A11",
    "audio": "assets/audio/chords/A/A11.mp3",
    "diagram": "assets/diagrams/A/A11.png"
   },
   {
    "type": "",
    "label": "A13",
    "audio": "assets/audio/chords/A/A13.mp3",
    "diagram": "assets/diagrams/A/A13.png"
   },
   {
    "type": "",
    "label": "A69",
    "audio": "assets/audio/chords/A/A69.mp3",
    "diagram": "assets/diagrams/A/A69.png"
   },
   {
    "type": "",
    "label": "Am6",
    "audio": "assets/audio/chords/A/Am6.mp3",
    "diagram": "assets/diagrams/A/Am6.png"
   },
   {
    "type": "",
    "label": "Am7",
    "audio": "assets/audio/chords/A/Am7.mp3",
    "diagram": "assets/diagrams/A/Am7.png"
   },
   {
    "type": "",
    "label": "Am9",
    "audio": "assets/audio/chords/A/Am9.mp3",
    "diagram": "assets/diagrams/A/Am9.png"
   },
   {
    "type": "",
    "label": "Aaug",
    "audio": "assets/audio/chords/A/Aaug.mp3",
    "diagram": "assets/diagrams/A/Aaug.png"
   },
   {
    "type": "",
    "label": "Adim",
    "audio": "assets/audio/chords/A/Adim.mp3",
    "diagram": "assets/diagrams/A/Adim.png"
   },
   {
    "type": "",
    "label": "Am69",
    "audio": "assets/audio/chords/A/Am69.mp3",
    "diagram": "assets/diagrams/A/Am69.png"
   },
   {
    "type": "",
    "label": "Aadd9",
    "audio": "assets/audio/chords/A/Aadd9.mp3",
    "diagram": "assets/diagrams/A/Aadd9.png"
   },
   {
    "type": "",
    "label": "Adim7",
    "audio": "assets/audio/chords/A/Adim7.mp3",
    "diagram": "assets/diagrams/A/Adim7.png"
   },
   {
    "type": "",
    "label": "Amaj7",
    "audio": "assets/audio/chords/A/Amaj7.mp3",
    "diagram": "assets/diagrams/A/Amaj7.png"
   },
   {
    "type": "",
    "label": "Amaj9",
    "audio": "assets/audio/chords/A/Amaj9.mp3",
    "diagram": "assets/diagrams/A/Amaj9.png"
   },
   {
    "type": "",
    "label": "Asus2",
    "audio": "assets/audio/chords/A/Asus2.mp3",
    "diagram": "assets/diagrams/A/Asus2.png"
   },
   {
    "type": "",
    "label": "Asus4",
    "audio": "assets/audio/chords/A/Asus4.mp3",
    "diagram": "assets/diagrams/A/Asus4.png"
   },
   {
    "type": "",
    "label": "A7sus4",
    "audio": "assets/audio/chords/A/A7sus4.mp3",
    "diagram": "assets/diagrams/A/A7sus4.png"
   },
   {
    "type": "",
    "label": "A9sus4",
    "audio": "assets/audio/chords/A/A9sus4.mp3",
    "diagram": "assets/diagrams/A/A9sus4.png"
   },
   {
    "type": "",
    "label": "AmMaj7",
    "audio": "assets/audio/chords/A/AmMaj7.mp3",
    "diagram": "assets/diagrams/A/AmMaj7.png"
   },
   {
    "type": "",
    "label": "AmMaj9",
    "audio": "assets/audio/chords/A/AmMaj9.mp3",
    "diagram": "assets/diagrams/A/AmMaj9.png"
   },
   {
    "type": "",
    "label": "Amadd9",
    "audio": "assets/audio/chords/A/Amadd9.mp3",
    "diagram": "assets/diagrams/A/Amadd9.png"
   },
   {
    "type": "",
    "label": "A7flat5",
    "audio": "assets/audio/chords/A/A7flat5.mp3",
    "diagram": "assets/diagrams/A/A7flat5.png"
   },
   {
    "type": "",
    "label": "A7flat9",
    "audio": "assets/audio/chords/A/A7flat9.mp3",
    "diagram": "assets/diagrams/A/A7flat9.png"
   },
   {
    "type": "",
    "label": "A7flat13",
    "audio": "assets/audio/chords/A/A7flat13.mp3",
    "diagram": "assets/diagrams/A/A7flat13.png"
   },
   {
    "type": "",
    "label": "A7sharp5",
    "audio": "assets/audio/chords/A/A7sharp5.mp3",
    "diagram": "assets/diagrams/A/A7sharp5.png"
   },
   {
    "type": "",
    "label": "A7sharp9",
    "audio": "assets/audio/chords/A/A7sharp9.mp3",
    "diagram": "assets/diagrams/A/A7sharp9.png"
   },
   {
    "type": "",
    "label": "Am7flat5",
    "audio": "assets/audio/chords/A/Am7flat5.mp3",
    "diagram": "assets/diagrams/A/Am7flat5.png"
   },
   {
    "type": "",
    "label": "Amsharp5",
    "audio": "assets/audio/chords/A/Amsharp5.mp3",
    "diagram": "assets/diagrams/A/Amsharp5.png"
   },
   {
    "type": "",
    "label": "A7sharp11",
    "audio": "assets/audio/chords/A/A7sharp11.mp3",
    "diagram": "assets/diagrams/A/A7sharp11.png"
   },
   {
    "type": "",
    "label": "AMaj7sus4",
    "audio": "assets/audio/chords/A/AMaj7sus4.mp3",
    "diagram": "assets/diagrams/A/AMaj7sus4.png"
   },
   {
    "type": "",
    "label": "Am7sharp5",
    "audio": "assets/audio/chords/A/Am7sharp5.mp3",
    "diagram": "assets/diagrams/A/Am7sharp5.png"
   },
   {
    "type": "",
    "label": "Amaj9sus4",
    "audio": "assets/audio/chords/A/Amaj9sus4.mp3",
    "diagram": "assets/diagrams/A/Amaj9sus4.png"
   },
   {
    "type": "",
    "label": "Amaj7flat5",
    "audio": "assets/audio/chords/A/Amaj7flat5.mp3",
    "diagram": "assets/diagrams/A/Amaj7flat5.png"
   },
   {
    "type": "",
    "label": "Amaj7sharp5",
    "audio": "assets/audio/chords/A/Amaj7sharp5.mp3",
    "diagram": "assets/diagrams/A/Amaj7sharp5.png"
   }
  ]
 },
 "Bb": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "Bb",
    "audio": "assets/audio/chords/Bb/Bb.mp3",
    "diagram": "assets/diagrams/Bb/Bb.png"
   },
   {
    "type": "",
    "label": "Bb6",
    "audio": "assets/audio/chords/Bb/Bb6.mp3",
    "diagram": "assets/diagrams/Bb/Bb6.png"
   },
   {
    "type": "",
    "label": "Bb7",
    "audio": "assets/audio/chords/Bb/Bb7.mp3",
    "diagram": "assets/diagrams/Bb/Bb7.png"
   },
   {
    "type": "",
    "label": "Bb9",
    "audio": "assets/audio/chords/Bb/Bb9.mp3",
    "diagram": "assets/diagrams/Bb/Bb9.png"
   },
   {
    "type": "",
    "label": "Bbm",
    "audio": "assets/audio/chords/Bb/Bbm.mp3",
    "diagram": "assets/diagrams/Bb/Bbm.png"
   },
   {
    "type": "",
    "label": "Bb11",
    "audio": "assets/audio/chords/Bb/Bb11.mp3",
    "diagram": "assets/diagrams/Bb/Bb11.png"
   },
   {
    "type": "",
    "label": "Bb13",
    "audio": "assets/audio/chords/Bb/Bb13.mp3",
    "diagram": "assets/diagrams/Bb/Bb13.png"
   },
   {
    "type": "",
    "label": "Bb69",
    "audio": "assets/audio/chords/Bb/Bb69.mp3",
    "diagram": "assets/diagrams/Bb/Bb69.png"
   },
   {
    "type": "",
    "label": "Bbm6",
    "audio": "assets/audio/chords/Bb/Bbm6.mp3",
    "diagram": "assets/diagrams/Bb/Bbm6.png"
   },
   {
    "type": "",
    "label": "Bbm7",
    "audio": "assets/audio/chords/Bb/Bbm7.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj7.png"
   },
   {
    "type": "",
    "label": "Bbm9",
    "audio": "assets/audio/chords/Bb/Bbm9.mp3",
    "diagram": "assets/diagrams/Bb/Bbm9.png"
   },
   {
    "type": "",
    "label": "Bbaug",
    "audio": "assets/audio/chords/Bb/Bbaug.mp3",
    "diagram": "assets/diagrams/Bb/Bbaug.png"
   },
   {
    "type": "",
    "label": "Bbdim",
    "audio": "assets/audio/chords/Bb/Bbdim.mp3",
    "diagram": "assets/diagrams/Bb/Bbdim.png"
   },
   {
    "type": "",
    "label": "Bbm69",
    "audio": "assets/audio/chords/Bb/Bbm69.mp3",
    "diagram": "assets/diagrams/Bb/Bbm69.png"
   },
   {
    "type": "",
    "label": "Bbadd9",
    "audio": "assets/audio/chords/Bb/Bbadd9.mp3",
    "diagram": "assets/diagrams/Bb/Bbadd9.png"
   },
   {
    "type": "",
    "label": "Bbdim7",
    "audio": "assets/audio/chords/Bb/Bbdim7.mp3",
    "diagram": "assets/diagrams/Bb/Bbdim7.png"
   },
   {
    "type": "",
    "label": "Bbmaj7",
    "audio": "assets/audio/chords/Bb/Bbmaj7.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj7.png"
   },
   {
    "type": "",
    "label": "Bbmaj9",
    "audio": "assets/audio/chords/Bb/Bbmaj9.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj9.png"
   },
   {
    "type": "",
    "label": "Bbsus2",
    "audio": "assets/audio/chords/Bb/Bbsus2.mp3",
    "diagram": "assets/diagrams/Bb/Bbsus2.png"
   },
   {
    "type": "",
    "label": "Bbsus4",
    "audio": "assets/audio/chords/Bb/Bbsus4.mp3",
    "diagram": "assets/diagrams/Bb/Bbsus4.png"
   },
   {
    "type": "",
    "label": "Bb7sus4",
    "audio": "assets/audio/chords/Bb/Bb7sus4.mp3",
    "diagram": "assets/diagrams/Bb/Bb7sus4.png"
   },
   {
    "type": "",
    "label": "Bb9sus4",
    "audio": "assets/audio/chords/Bb/Bb9sus4.mp3",
    "diagram": "assets/diagrams/Bb/Bb9sus4.png"
   },
   {
    "type": "",
    "label": "BbmMaj7",
    "audio": "assets/audio/chords/Bb/BbmMaj7.mp3",
    "diagram": "assets/diagrams/Bb/BbmMaj7.png"
   },
   {
    "type": "",
    "label": "BbmMaj9",
    "audio": "assets/audio/chords/Bb/BbmMaj9.mp3",
    "diagram": "assets/diagrams/Bb/BbmMaj9.png"
   },
   {
    "type": "",
    "label": "Bbmadd9",
    "audio": "assets/audio/chords/Bb/Bbmadd9.mp3",
    "diagram": "assets/diagrams/Bb/Bbmadd9.png"
   },
   {
    "type": "",
    "label": "Bb7flat5",
    "audio": "assets/audio/chords/Bb/Bb7flat5.mp3",
    "diagram": "assets/diagrams/Bb/Bb7flat5.png"
   },
   {
    "type": "",
    "label": "Bb7flat9",
    "audio": "assets/audio/chords/Bb/Bb7flat9.mp3",
    "diagram": "assets/diagrams/Bb/Bb7flat9.png"
   },
   {
    "type": "",
    "label": "Bb7flat13",
    "audio": "assets/audio/chords/Bb/Bb7flat13.mp3",
    "diagram": "assets/diagrams/Bb/Bb7flat13.png"
   },
   {
    "type": "",
    "label": "Bb7sharp5",
    "audio": "assets/audio/chords/Bb/Bb7sharp5.mp3",
    "diagram": "assets/diagrams/Bb/Bb7sharp5.png"
   },
   {
    "type": "",
    "label": "Bb7sharp9",
    "audio": "assets/audio/chords/Bb/Bb7sharp9.mp3",
    "diagram": "assets/diagrams/Bb/Bb7sharp9.png"
   },
   {
    "type": "",
    "label": "Bbm7flat5",
    "audio": "assets/audio/chords/Bb/Bbm7flat5.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj7flat5.png"
   },
   {
    "type": "",
    "label": "Bbmsharp5",
    "audio": "assets/audio/chords/Bb/Bbmsharp5.mp3",
    "diagram": "assets/diagrams/Bb/Bbmsharp5.png"
   },
   {
    "type": "",
    "label": "Bb7sharp11",
    "audio": "assets/audio/chords/Bb/Bb7sharp11.mp3",
    "diagram": "assets/diagrams/Bb/Bb7sharp11.png"
   },
   {
    "type": "",
    "label": "BbMaj7sus4",
    "audio": "assets/audio/chords/Bb/BbMaj7sus4.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj7sus4.png"
   },
   {
    "type": "",
    "label": "BbMaj9sus4",
    "audio": "assets/audio/chords/Bb/BbMaj9sus4.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj9sus4.png"
   },
   {
    "type": "",
    "label": "Bbm7sharp5",
    "audio": "assets/audio/chords/Bb/Bbm7sharp5.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj7sharp5.png"
   },
   {
    "type": "",
    "label": "Bbmaj7flat5",
    "audio": "assets/audio/chords/Bb/Bbmaj7flat5.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj7flat5.png"
   },
   {
    "type": "",
    "label": "Bbmaj7sharp5",
    "audio": "assets/audio/chords/Bb/Bbmaj7sharp5.mp3",
    "diagram": "assets/diagrams/Bb/BbMaj7sharp5.png"
   }
  ]
 },
 "B": {
  "rootAudio": null,
  "chords": [
   {
    "type": "",
    "label": "B",
    "audio": "assets/audio/chords/B/B.mp3",
    "diagram": "assets/diagrams/B/B.png"
   },
   {
    "type": "",
    "label": "B6",
    "audio": "assets/audio/chords/B/B6.mp3",
    "diagram": "assets/diagrams/B/B6.png"
   },
   {
    "type": "",
    "label": "B7",
    "audio": "assets/audio/chords/B/B7.mp3",
    "diagram": "assets/diagrams/B/B7.png"
   },
   {
    "type": "",
    "label": "B9",
    "audio": "assets/audio/chords/B/B9.mp3",
    "diagram": "assets/diagrams/B/B9.png"
   },
   {
    "type": "",
    "label": "Bm",
    "audio": "assets/audio/chords/B/Bm.mp3",
    "diagram": "assets/diagrams/B/Bm.png"
   },
   {
    "type": "",
    "label": "B11",
    "audio": "assets/audio/chords/B/B11.mp3",
    "diagram": "assets/diagrams/B/B11.png"
   },
   {
    "type": "",
    "label": "B13",
    "audio": "assets/audio/chords/B/B13.mp3",
    "diagram": "assets/diagrams/B/B13.png"
   },
   {
    "type": "",
    "label": "B69",
    "audio": "assets/audio/chords/B/B69.mp3",
    "diagram": "assets/diagrams/B/B69.png"
   },
   {
    "type": "",
    "label": "Bm6",
    "audio": "assets/audio/chords/B/Bm6.mp3",
    "diagram": "assets/diagrams/B/Bm6.png"
   },
   {
    "type": "",
    "label": "Bm7",
    "audio": "assets/audio/chords/B/Bm7.mp3",
    "diagram": "assets/diagrams/B/Bm7.png"
   },
   {
    "type": "",
    "label": "Bm9",
    "audio": "assets/audio/chords/B/Bm9.mp3",
    "diagram": "assets/diagrams/B/Bm9.png"
   },
   {
    "type": "",
    "label": "Baug",
    "audio": "assets/audio/chords/B/Baug.mp3",
    "diagram": "assets/diagrams/B/Baug.png"
   },
   {
    "type": "",
    "label": "Bdim",
    "audio": "assets/audio/chords/B/Bdim.mp3",
    "diagram": "assets/diagrams/B/Bdim.png"
   },
   {
    "type": "",
    "label": "Bm69",
    "audio": "assets/audio/chords/B/Bm69.mp3",
    "diagram": "assets/diagrams/B/Bm69.png"
   },
   {
    "type": "",
    "label": "Badd9",
    "audio": "assets/audio/chords/B/Badd9.mp3",
    "diagram": "assets/diagrams/B/Badd9.png"
   },
   {
    "type": "",
    "label": "Bdim7",
    "audio": "assets/audio/chords/B/Bdim7.mp3",
    "diagram": "assets/diagrams/B/Bdim7.png"
   },
   {
    "type": "",
    "label": "Bmaj7",
    "audio": "assets/audio/chords/B/Bmaj7.mp3",
    "diagram": "assets/diagrams/B/Bmaj7.png"
   },
   {
    "type": "",
    "label": "Bmaj9",
    "audio": "assets/audio/chords/B/Bmaj9.mp3",
    "diagram": "assets/diagrams/B/Bmaj9.png"
   },
   {
    "type": "",
    "label": "Bsus2",
    "audio": "assets/audio/chords/B/Bsus2.mp3",
    "diagram": "assets/diagrams/B/Bsus2.png"
   },
   {
    "type": "",
    "label": "Bsus4",
    "audio": "assets/audio/chords/B/Bsus4.mp3",
    "diagram": "assets/diagrams/B/Bsus4.png"
   },
   {
    "type": "",
    "label": "B7sus4",
    "audio": "assets/audio/chords/B/B7sus4.mp3",
    "diagram": "assets/diagrams/B/B7sus4.png"
   },
   {
    "type": "",
    "label": "B9sus4",
    "audio": "assets/audio/chords/B/B9sus4.mp3",
    "diagram": "assets/diagrams/B/B9sus4.png"
   },
   {
    "type": "",
    "label": "BmMaj7",
    "audio": "assets/audio/chords/B/BmMaj7.mp3",
    "diagram": "assets/diagrams/B/BmMaj7.png"
   },
   {
    "type": "",
    "label": "BmMaj9",
    "audio": "assets/audio/chords/B/BmMaj9.mp3",
    "diagram": "assets/diagrams/B/BmMaj9.png"
   },
   {
    "type": "",
    "label": "Bmadd9",
    "audio": "assets/audio/chords/B/Bmadd9.mp3",
    "diagram": "assets/diagrams/B/Bmadd9.png"
   },
   {
    "type": "",
    "label": "B7flat5",
    "audio": "assets/audio/chords/B/B7flat5.mp3",
    "diagram": "assets/diagrams/B/B7flat5.png"
   },
   {
    "type": "",
    "label": "B7flat9",
    "audio": "assets/audio/chords/B/B7flat9.mp3",
    "diagram": "assets/diagrams/B/B7flat9.png"
   },
   {
    "type": "",
    "label": "B7flat13",
    "audio": "assets/audio/chords/B/B7flat13.mp3",
    "diagram": "assets/diagrams/B/B7flat13.png"
   },
   {
    "type": "",
    "label": "B7sharp5",
    "audio": "assets/audio/chords/B/B7sharp5.mp3",
    "diagram": "assets/diagrams/B/B7sharp5.png"
   },
   {
    "type": "",
    "label": "B7sharp9",
    "audio": "assets/audio/chords/B/B7sharp9.mp3",
    "diagram": "assets/diagrams/B/B7sharp9.png"
   },
   {
    "type": "",
    "label": "Bm7flat5",
    "audio": "assets/audio/chords/B/Bm7flat5.mp3",
    "diagram": "assets/diagrams/B/Bm7flat5.png"
   },
   {
    "type": "",
    "label": "Bmsharp5",
    "audio": "assets/audio/chords/B/Bmsharp5.mp3",
    "diagram": "assets/diagrams/B/Bmsharp5.png"
   },
   {
    "type": "",
    "label": "B7sharp11",
    "audio": "assets/audio/chords/B/B7sharp11.mp3",
    "diagram": "assets/diagrams/B/B7sharp11.png"
   },
   {
    "type": "",
    "label": "BMaj7sus4",
    "audio": "assets/audio/chords/B/BMaj7sus4.mp3",
    "diagram": "assets/diagrams/B/BMaj7sus4.png"
   },
   {
    "type": "",
    "label": "Bm7sharp5",
    "audio": "assets/audio/chords/B/Bm7sharp5.mp3",
    "diagram": "assets/diagrams/B/Bm7sharp5.png"
   },
   {
    "type": "",
    "label": "Bmaj9sus4",
    "audio": "assets/audio/chords/B/Bmaj9sus4.mp3",
    "diagram": "assets/diagrams/B/Bmaj9sus4.png"
   },
   {
    "type": "",
    "label": "Bmaj7flat5",
    "audio": "assets/audio/chords/B/Bmaj7flat5.mp3",
    "diagram": "assets/diagrams/B/Bmaj7flat5.png"
   },
   {
    "type": "",
    "label": "Bmaj7sharp5",
    "audio": "assets/audio/chords/B/Bmaj7sharp5.mp3",
    "diagram": "assets/diagrams/B/Bmaj7sharp5.png"
   }
  ]
 }
};
if (typeof module !== 'undefined') module.exports = { ROOTS, DATA };
